name: Generate terraform docs
on:
  pull_request:
    types:
    - closed
    branches:
    - main

permissions:
  contents: write

jobs:
  generate-terraform-docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.ref }}

    - name: Render terraform docs and push changes back to PR
      uses: terraform-docs/gh-actions@main
      with:
        recursive: true
        config-file: .terraform-docs.yml
        output-file: README.md
        output-method: inject
        git-push: "true"
